export const TYPE = 'TYPE';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';
export const CREATE_ENTRY_SUCCESS = 'CREATE_ENTRY_SUCCESS';
export const CREATE_ENTRY_FAILURE = 'CREATE_ENTRY_FAILURE';
export const GET_USER_STAT_SUCCESS = 'GET_USER_STAT_SUCCESS';
export const GET_USER_STAT_FAILURE = 'GET_USER_STAT_FAILURE';
